/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package makingPizza;

import java.text.DecimalFormat;

/**
 *
 * @author evrob0095
 */
public class makingPizza extends javax.swing.JFrame {

    /**
     * Creates new form makingPizza
     */
    public makingPizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        title1Label = new javax.swing.JLabel();
        title2Label = new javax.swing.JLabel();
        diameterInput = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        diameterLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        customTextLabel = new javax.swing.JLabel();
        totalLabel1 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(153, 255, 153));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        messageLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(255, 0, 0));
        panel.add(messageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 160, 30));

        title1Label.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 36)); // NOI18N
        title1Label.setForeground(new java.awt.Color(255, 0, 0));
        title1Label.setText("Papa John's Pizza Joint");
        panel.add(title1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 310, 50));

        title2Label.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 36)); // NOI18N
        title2Label.setText("Papa John's Pizza Joint");
        panel.add(title2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        diameterInput.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        panel.add(diameterInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 100, 30));

        calculateButton.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        calculateButton.setText("Calculate Cost");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });
        panel.add(calculateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 110, -1));

        diameterLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        diameterLabel.setForeground(new java.awt.Color(255, 0, 0));
        diameterLabel.setText("Diameter of Pizza in centimeters");
        panel.add(diameterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 290, 30));

        subtotalLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        subtotalLabel.setForeground(new java.awt.Color(255, 0, 0));
        subtotalLabel.setText("Subtotal:");
        panel.add(subtotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 160, 30));

        taxLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        taxLabel.setForeground(new java.awt.Color(255, 0, 0));
        taxLabel.setText("Tax:");
        panel.add(taxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 160, 30));

        customTextLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        customTextLabel.setForeground(new java.awt.Color(255, 0, 0));
        panel.add(customTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 370, 50));

        totalLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        totalLabel1.setForeground(new java.awt.Color(255, 0, 0));
        totalLabel1.setText("Total:");
        panel.add(totalLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 160, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makingPizza/pizza_trad_pepperoni.png"))); // NOI18N
        panel.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        descriptionLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(255, 0, 0));
        descriptionLabel.setText("We only sell this pizza right here");
        panel.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        
        //Varibales and Constants
        int pizzaDiameter;
        double subtotal;
        double total;
        double taxTotal;
        final double TAX = 0.13;
        final double INGREDIENT_COST = 0.50;
        final double RENT_COST = 0.99;
        final double LABOUR_COST = 0.75;
        
        DecimalFormat x = new DecimalFormat("$#,###,###.00");
        
        pizzaDiameter = Integer.parseInt(diameterInput.getText());
        
        //Calculations
        subtotal = (pizzaDiameter*INGREDIENT_COST) + RENT_COST + LABOUR_COST;
        taxTotal = (subtotal*TAX);
        total = (subtotal+taxTotal);
        
        //Execution
        subtotalLabel.setText("Subtotal: " + x.format(subtotal));
        taxLabel.setText("Tax: " + x.format(taxTotal));
        totalLabel1.setText("Total: " + x.format(total));
        
        if (pizzaDiameter <= 15 && pizzaDiameter > 0) {
            customTextLabel.setText("We are going to make you a cute little pizza!");
        }
        else if (pizzaDiameter > 15 && pizzaDiameter <= 40) {
            customTextLabel.setText("This will be delicious!");
        }
        else if (pizzaDiameter > 40) {
            customTextLabel.setText("Whoa, big pizza! You might need a truck to get this home!");
        }
        else if (pizzaDiameter < 0) {
            customTextLabel.setText("Nice try bucko, that's a negative number!");
        }
        
    }//GEN-LAST:event_calculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(makingPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(makingPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(makingPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(makingPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new makingPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel customTextLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField diameterInput;
    private javax.swing.JLabel diameterLabel;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel title1Label;
    private javax.swing.JLabel title2Label;
    private javax.swing.JLabel totalLabel1;
    // End of variables declaration//GEN-END:variables
}
